## Importin libraries

In [19]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [20]:
df = pd.read_csv('credit_data.csv')
df

clientid        income        age         loan       LTI  default
0            1  66155.925095  59.017015  8106.532131  0.122537        0
1            2  34415.153966  48.117153  6564.745018  0.190752        0
2            3  57317.170063  63.108049  8020.953296  0.139940        0
3            4  42709.534201  45.751972  6103.642260  0.142911        0
4            5  66952.688845  18.584336  8770.099235  0.130989        1
...        ...           ...        ...          ...       ...      ...
1995      1996  59221.044874  48.518179  1926.729397  0.032535        0
1996      1997  69516.127573  23.162104  3503.176156  0.050394        0
1997      1998  44311.449262  28.017167  5522.786693  0.124636        1
1998      1999  43756.056605  63.971796  1622.722598  0.037086        0
1999      2000  69436.579552  56.152617  7378.833599  0.106267        0

[2000 rows x 6 columns]

In [21]:
X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values

In [22]:
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03, 1.22536751e-01],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03, 1.90751581e-01],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03, 1.39939800e-01],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03, 1.24635659e-01],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03, 3.70856682e-02],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03, 1.06267239e-01]])

## Spliting the dataset into training set and test set

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [24]:
X_train

array([[3.09914319e+04, 3.40100260e+01, 4.58926727e+03, 1.48081808e-01],
       [3.18478537e+04, 4.14163358e+01, 2.91376993e+03, 9.14903075e-02],
       [2.41124994e+04, 3.59713375e+01, 3.28549995e+03, 1.36257129e-01],
       ...,
       [4.84451131e+04, 3.89795677e+01, 8.73344221e+03, 1.80274989e-01],
       [5.37413710e+04, 4.97294326e+01, 6.51315012e+03, 1.21194342e-01],
       [5.51162345e+04, 4.14688852e+01, 1.02846068e+04, 1.86598502e-01]])

## Feature Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building an ann

In [26]:
# initializing the ann
ann = tf.keras.models.Sequential()

In [27]:
# adding the first input layer and the first hidden layer 
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [28]:
# adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [29]:
# adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

In [31]:
# compiling ann
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [33]:
# training the ann on training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0087 - accuracy: 0.9994
Epoch 2/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0084 - accuracy: 0.9994
Epoch 3/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0083 - accuracy: 0.9994
Epoch 4/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0081 - accuracy: 0.9994
Epoch 5/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0081 - accuracy: 1.0000
Epoch 6/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0079 - accuracy: 0.9994
Epoch 7/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0079 - accuracy: 0.9994
Epoch 8/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0080 - accuracy: 0.9994
Epoch 9/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0078 - accuracy: 0.9994
Epoch 10/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0077 - accuracy: 0.9994
Epoch 11/

50/50 [==============================] - 0s 2ms/step - loss: 0.0045 - accuracy: 0.9994
Epoch 84/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 0.9994
Epoch 85/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 0.9994
Epoch 86/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 0.9994
Epoch 87/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0044 - accuracy: 0.9994
Epoch 88/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 0.9994
Epoch 89/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 0.9994
Epoch 90/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 0.9994
Epoch 91/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0040 - accuracy: 0.9994
Epoch 92/100
50/50 [==============================] - 0s 3ms/step - loss: 0.0043 - accuracy: 0.9994
Epoch 93/100


## Predicting the test result

In [34]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]

In [37]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[347   1]
 [  0  52]]


0.9975

## building ann for sgd

In [38]:
# initializing the ann
ann = tf.keras.models.Sequential()

In [39]:
# adding the first input layer and the first hidden layer 
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [40]:
# adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [41]:
# adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## training ann for sgd

In [42]:
# compiling ann
ann.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [43]:
# training the ann on training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
50/50 [==============================] - 1s 3ms/step - loss: 0.7332 - accuracy: 0.4594
Epoch 2/100
50/50 [==============================] - 0s 2ms/step - loss: 0.6226 - accuracy: 0.7513
Epoch 3/100
50/50 [==============================] - 0s 2ms/step - loss: 0.5523 - accuracy: 0.8487
Epoch 4/100
50/50 [==============================] - 0s 2ms/step - loss: 0.5003 - accuracy: 0.8556
Epoch 5/100
50/50 [==============================] - 0s 2ms/step - loss: 0.4560 - accuracy: 0.8556
Epoch 6/100
50/50 [==============================] - 0s 2ms/step - loss: 0.4156 - accuracy: 0.8556
Epoch 7/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3806 - accuracy: 0.8556
Epoch 8/100
50/50 [==============================] - 0s 3ms/step - loss: 0.3525 - accuracy: 0.8556
Epoch 9/100
50/50 [==============================] - 0s 3ms/step - loss: 0.3295 - accuracy: 0.8587
Epoch 10/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3092 - accuracy: 0.8656
Epoch 11/

50/50 [==============================] - 0s 1ms/step - loss: 0.0689 - accuracy: 0.9688
Epoch 84/100
50/50 [==============================] - 0s 1ms/step - loss: 0.0683 - accuracy: 0.9700
Epoch 85/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0677 - accuracy: 0.9700
Epoch 86/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0670 - accuracy: 0.9725
Epoch 87/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0663 - accuracy: 0.9719
Epoch 88/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0658 - accuracy: 0.9706
Epoch 89/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0652 - accuracy: 0.9725
Epoch 90/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0646 - accuracy: 0.9725
Epoch 91/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0640 - accuracy: 0.9725
Epoch 92/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0633 - accuracy: 0.9731
Epoch 93/100


## predicting the result 

In [44]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]

In [45]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[344   4]
 [  2  50]]


0.985